### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by trzonne** [Eng-Elias/CrewAI-Visualizer#10]
1. Somehow every step I take ends up with errors, to my frustration. Tried your automated scripts first, and then later step by step manually.
Tried to install postgresql and did not understand how or where to set user/pass information? Can't find it on their site as well. You have information on that?

2. Then, in trying to fixing the installation of postgresql, things went south quickly. There was a problem with a double security key (which I fixed by removing an entry deep in the system). Also I fiddled with its system folders, and now there is an error in the dpkg file.
Because it misses some essential postgresql files (stored in /usr/share/postgresql-common) it cannot properly install or deinstall itself anymore.
I figure I want to force a reinstallation of the whole package (fixing dgpk does not work), and then deleting it so I can start from scratch again.

As I am still novice on Linux and get lost pretty quickly, you have any experiences with installation problems with postgresql? Can I simply 'sudo apt -force postgresq' or something to do a "no questions and checks overwriting installation" of the package? Perhaps you have some clues? Otherwise I think of reinstalling Ubuntu (for the third time this week argh...)

Thanks for any thoughts about this

**Comment by Eng-Elias** [comment]
For the issue of installing `PostgreSQL`, this is the official docs: https://www.postgresql.org/download/linux/ubuntu/ 
You can follow it it is simple.
And this is for uninstalling PostgreSQL: https://askubuntu.com/questions/32730/how-to-remove-postgres-from-my-installation 
 

to fix the issue of `dpkg`, I think you need to uninstall and reinstall it with apt: https://ioflood.com/blog/install-dpkg-command-linux/#:~:text=In%20most%20Linux%20distributions%2C%20the,command%20sudo%20dpkg%20%2Di%20package.


for the username and password of PostgreSQL, it is included in the URL in `.env` file: 
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/crew_ai_visualizer?schema=public"
DATABASE_URL="postgresql://username:password@localhost:5432/crew_ai_visualizer?schema=public"
 
Try these solution and it you faced any new issues, let me know. 
And if these solutions work for you, please let me know too.

**Comment by setownley** [comment]
I couldn't see where the install doc's mention you need node installed.

**Comment by Eng-Elias** [comment]
> I couldn't see where the install doc's mention you need node installed.

The project was built with Next.js, which a JS framework and JS frameworks need Node.js to develop, build and run the project. 

In addition, I mentioned that I used `node-calls-python` package and its name tells you that you need Node.js and Python to use this package.

**Comment by trzonne** [comment]
For me it is closed. Changed OS and did not try the visualizer (yet)
