### ISSUE TITLE
Database `crew_ai_visualizer` does not exist on the database server at `localhost:5432`.

### ISSUE THREAD

**Issue by stevensu1977** [Eng-Elias/CrewAI-Visualizer#2]
I follow readme setup this project , but got error message : "Database `crew_ai_visualizer` does not exist on the database server at `localhost:5432`." .  Did I  missed something ?

**Comment by Eng-Elias** [comment]
Yes, you need to install PostgreSQL and apply the migrations with these commands: 

```
npx prisma generate
npx prisma migrate dev
```

I work now on V0.2 and I will add these notes to the README.md file.
