### ISSUE TITLE
Error message say TypeError CNo module named 'crewai' error when clicking run

### ISSUE THREAD

**Issue by Chuck-iykyk** [Eng-Elias/CrewAI-Visualizer#5]
Clicking run I get the error on the page shown. In the terminal
Is this:
"public"."Agent"."verbose", "public"."Agent"."memory", "public"."Agent"."image", "public"."Agent"."createdAt", "public"."Agent"."updatedAt" FROM "public"."Agent" WHERE "public"."Agent"."id" IN ($1,$2,$3,$4,$5,$6) OFFSET $7
No module named 'crewai'
![image_2024-03-30_154257810](https://github.com/Eng-Elias/CrewAI-Visualizer/assets/152994244/9ebb5b86-e7dd-409b-b5ae-7047519741cf)

**Comment by Eng-Elias** [comment]
This is just a Prisma query description: 
```
"public"."Agent"."verbose", "public"."Agent"."memory", "public"."Agent"."image", "public"."Agent"."createdAt", "public"."Agent"."updatedAt" FROM "public"."Agent" WHERE "public"."Agent"."id" IN ($1,$2,$3,$4,$5,$6) OFFSET $7
```

But this is the error: 
```
No module named 'crewai'
```

The Solution:
Ensure that you installed `crewai` in the `venv` and check the `PYTHON_SITE_PACKAGES` variable in `.env` file if you didn't create the `venv` in the project folder directly. 

Note:
Anyway the easiest way to install the project is to use `setup.bat` or `setup.sh` files. read the `README` for more details.

**Comment by Eng-Elias** [comment]
@Chuck-iykyk Please let me know if the problem is solved.

**Comment by Chuck-iykyk** [comment]
it looks right. 

![image_2024-03-31_140410009](https://github.com/Eng-Elias/CrewAI-Visualizer/assets/152994244/63316da4-f999-4261-abbc-9a73f1711d0e)

**Comment by Eng-Elias** [comment]
The name of the folder must be `venv` not '.venv' and it must be the project folder directly.

**Comment by Chuck-iykyk** [comment]
thanks good catch!  I fixed the script. Now I get prism errors trying to pull up missions I created previously.
I will reinstall.

**Comment by Eng-Elias** [comment]
Yes, I suggest to reinstall it, it will reapply the migrations and I hope it will work fine. 
Please let me know when you can run the project.

**Comment by Chuck-iykyk** [comment]
After reinstall runing the bat. I see this in the vscode terminal
![image_2024-03-31_143647655](https://github.com/Eng-Elias/CrewAI-Visualizer/assets/152994244/ea972e95-e9a6-4c56-b206-2d90f7ecf9f7)

The app starts then I see this when clicking on Mission section:
![image_2024-03-31_143730084](https://github.com/Eng-Elias/CrewAI-Visualizer/assets/152994244/af3ae0d7-0652-4261-9da5-a5df93ccefd2)
Checking postgres I see the crew_ai_visualizer database but no tables.

**Comment by Eng-Elias** [comment]
try to delete the database then reinstall

**Comment by Chuck-iykyk** [comment]
new build on windows server. I still get the zero length error and no tables in the crew_ai database.
![image_2024-04-01_163259614](https://github.com/Eng-Elias/CrewAI-Visualizer/assets/152994244/7b5426e6-c36f-4d80-afc8-55d0fa609d74)

**Comment by Chuck-iykyk** [comment]
I just ran the *.sql and now the app comes up.

**Comment by Eng-Elias** [comment]
I think, if you ran this command before migrate, it might solve the issue: 
`call npx prisma generate` 

Anyway, I am happy, you could solve the issue.
