### ISSUE TITLE
Getting error when trying to run a task:

### ISSUE THREAD

**Issue by r3c0n75** [Eng-Elias/CrewAI-Visualizer#6]
Setup PostgreSQL then installed CrewAI-Visualizer on Windows 11 via script "setup_win.bat"; no issues. Ran the "start_win.bat" to start the program. Create an agent called "Writer" with all tools enabled as a test. Created a mission and a task and assigend it to the "Writer"

Getting error when trying to run a task:
Error
1 validation error for ChatGoogleGenerativeAI __root__ Did not find google_api_key, please add an environment variable `GOOGLE_API_KEY` which contains it, or pass `google_api_key` as a named parameter. (type=value_error)
<img width="405" alt="image" src="https://github.com/Eng-Elias/CrewAI-Visualizer/assets/166418478/f0af1fac-c873-4f92-ab68-c40acb84be2c">

**Comment by Eng-Elias** [comment]
@r3c0n75 See the "Configuration" section in README. 
You just need to rename .env.template into .env and set your "GEMINI_API_KEY".

**Comment by r3c0n75** [comment]
I'm a bit new to some of this so I appreciate your help. I generated a new key from "https://aistudio.google.com/app/apikey" and that seems to fix it as I am now seeing search results in the terminal.  Thank you for the quick response!!!
