### ISSUE TITLE
llm's?

### ISSUE THREAD

**Issue by Kelbresqe** [Eng-Elias/CrewAI-Visualizer#7]
how can i change llm model to free model like groq or local model like ollama?

**Comment by Eng-Elias** [comment]
For now the project use Gemini only, but Gemini is LLM from Google and it is free in limit 60 queries per minute. 
I will add more LLMs in future versions. 
Until then, you can fork/clone the project and update the code to add LLMs you want.

**Comment by Kelbresqe** [comment]
Thank you for your response. Of course, cost is important, but privacy and speed are also crucial. I asked about Groq for its speed to test it. Ollama is the solution I always use for security. I couldn't find the setting related to Gemini in the codes. If you share where you set it, I will try to make changes. I am not as skilled in coding as you are. Thank you.

**Comment by Eng-Elias** [comment]
You need to update this file: 
`src/app/api/graphql/crewai.py`

You can use langchain_community package to define Ollama LLM replacing this code with the following code:

```python
from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-pro",
    verbose=True,
    temperature=0.5,
    google_api_key=os.getenv("GEMINI_API_KEY"),
)
```

```python
#import Ollama
from langchain_community.llms import Ollama

#define the LLM
llm = Ollama(model="llama3")
``` 

I think this will work for you. 
For more details check the official docs: 
https://python.langchain.com/docs/integrations/llms/ollama/

Let me know if you need more help and if this solution worked for you.

**Comment by Kelbresqe** [comment]
Thank you for your help
